apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db-secret
type: Opaque
data:
  root-password: {{ .Values.mariadb.rootPassword | b64enc }}
  username: {{ .Values.mariadb.username | b64enc }}
  password: {{ .Values.mariadb.password | b64enc }}
  database: {{ .Values.mariadb.database | b64enc }}