apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-service
spec:
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
  type: LoadBalancer