apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - port: {{ .Values.mariadb.port }}
    targetPort: {{ .Values.mariadb.port }}
  type: ClusterIP
  clusterIP: None